#!/usr/bin/env bash
# Bash script that transfers a file from our client to a server
number_args = "$#"
if [[ number_args < 3 ]]
then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
	scp root@bccd33b2ab31:/root/alx-system_engineering-devops/0x0C-web_server/my_file ubuntu@54.237.65.34:/~/
fi
