#!/usr/bin/env bash
# Bash script that transfers a file from our client to a server
args=$#
if [[ args -lt 3 ]]
then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
	scp -i $4 $1 ubuntu@$2:~/
fi
