#!/usr/bin/env bash
# Bash script that configures a new Ubuntu machine
sudo apt update

sudo apt install nginx

echo Hello World! > /var/www/html/index.nginx-debian.html
sed -i 's/listen 8080;/listen 80;/' /etc/nginx/nginx.conf
