#!/usr/bin/env bash
# Bash script that configures a new Ubuntu machine
sudo apt-get update

sudo apt-get install nginx

echo "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html
#sed -i 's/listen 8080;/listen 80;/' /etc/nginx/nginx.conf

sudo service nginx restart
