#!/usr/bin/env bash
# Bash script that configures a new Ubuntu machine
server {
    listen 80;

    location / {
        add_header Content-Type text/html;

        return 200 '<html><body>Hello World</body></html>';
    }
}
