#!/usr/bin/env bash
# Configure Nginx so that its HTTP response contains a custom header (on web-01 and web-02)
# The name of the custom HTTP header must be X-Served-By
# The value of the custom HTTP header must be the hostname of the server Nginx is running on
ssh -i ~/.ssh/school ubuntu@54.237.19.164
ssh -i ~/.ssh/school ubuntu@54.174.170.184
ssh -i ~/.ssh/school ubuntu@100.25.157.87

sudo apt-get update
sudo apt-get -y install nginx

echo "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html
sudo sh -c 'echo "Hello World!" > /var/www/html/index.nginx-debian.html'
sudo sed -i '/^}$/i \ \n\tlocation \/redirect_me {return 301 https:\/\/www.youtube.com\/watch?v=QH2-TGUlwu4;}' /etc/nginx/sites-available/default
sudo sed -i 's/add_header X-Served-By \$hostname;/' /etc/nginx/site-available/default
sudo service nginx restart
