#!/usr/bin/env bash
# Install and configure HAproxy on your lb-01 server.
# Configure HAproxy so that it send traffic to web-01 and web-02
# Distribute requests using a roundrobin algorithm

sudo apt-get install -y haproxy

echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

cat <<EOT | sudo tee -a /etc/haproxy/haproxy.cfg
frontend aicha-domain.tech
    timeout client  30000
    bind 0:80
    default_backend aicha-domain.tech_backend

backend aicha-domain.tech_backend
    timeout connect  3000
    timeout server  30000
    balance roundrobin
    server 393788-web-01 54.236.41.36:80 check
    server 393788-web-02 52.91.156.164:80 check
EOT

sudo service haproxy restart
